#!/bin/bash

# Put your code here
# You may only use the following external programs: ls, echo, awk, cat, grep, sort, wc, bc
# Order resumes based on certain Keywords

argArray=()

for file in submissions/*
do
	argArray+=($file)
done

#echo ${argArray[@]}

gawk 'BEGIN{
	while((getline line <"input.txt") > 0){
		match(line,/([[:digit:].]+)/,a);
		split(line,ar,a[1]);
		ar[1]=substr(ar[1],1,length(ar[1])-1);
		Map[ar[1]]=a[1];
	}
	Total = 0;
	split("",filenames)
}
{
	#for(k in Map){
	#	Total+=Map[k]*gsub(/k/,"");
	#	print gsub(/k/,"");
	#}
	#(FNR==1)&&(NR!=1)
	if(fname != FILENAME){ #FNR counts the number of lines in the new input field starting with 1!
		Map1[FILENAME]=Total; #Maps Filename to total
		#Reset total
		Total=0
	}
	for(k in Map){
		Total+=Map[k]*gsub(/k/,"");
		print Map[k]*gsub(/k/,"");
	}
	#print NR,FNR
	fname=FILENAME
}
END{
	

}' ${argArray[@]}



