#!/bin/bash

# Put your code here
# You may only use the following external programs: ls, echo, awk, cat, grep, sort, wc, bc
# Order resumes based on certain Keywords

ls submissions | gawk 'BEGIN{
	while((getline line < "input.txt") > 0){
		match(line,/([[:digit:].]+)/,a);
		split(line,ar,a[1]);
		ar[1]=substr(ar[1],1,length(ar[1])-1);
		Map[ar[1]]=a[1];
	}
}
{
	Total=0
	for(k in Map){
		"grep -i -o \"" k "\" submissions/" $0 " | wc -l" | getline n
		Total+=Map[k]*n
	}
	Map1[$0]=Total
}
END{
	n=asort(Map1,values)
	k=asort(Map1,values2)
	for(j=1; j<=k; j++){
		for(f in Map1){
			if(values2[j]==Map1[f]){
				values2[j]=f;
				delete Map1[f];
			}
		}
	}
	for(l=n; l>=1; l--){
		print values[l],values2[l]
	}
}'



